version: "3.9"
services:
  kanat_app:
    build: ./KanatApp
    volumes:
     -  ./KanatApp:/go/src/KanatApp
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: alvistack/postgres-12
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
